// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt.proto

package jwt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blank) Reset()         { *m = Blank{} }
func (m *Blank) String() string { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()    {}
func (*Blank) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{0}
}

func (m *Blank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blank.Unmarshal(m, b)
}
func (m *Blank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blank.Marshal(b, m, deterministic)
}
func (m *Blank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blank.Merge(m, src)
}
func (m *Blank) XXX_Size() int {
	return xxx_messageInfo_Blank.Size(m)
}
func (m *Blank) XXX_DiscardUnknown() {
	xxx_messageInfo_Blank.DiscardUnknown(m)
}

var xxx_messageInfo_Blank proto.InternalMessageInfo

type HealthResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{1}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type JwtGenerateRequest struct {
	Exp                  int32           `protobuf:"varint,1,opt,name=exp,proto3" json:"exp,omitempty"`
	Short                bool            `protobuf:"varint,2,opt,name=short,proto3" json:"short,omitempty"`
	Message              string          `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Data                 *_struct.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JwtGenerateRequest) Reset()         { *m = JwtGenerateRequest{} }
func (m *JwtGenerateRequest) String() string { return proto.CompactTextString(m) }
func (*JwtGenerateRequest) ProtoMessage()    {}
func (*JwtGenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{2}
}

func (m *JwtGenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtGenerateRequest.Unmarshal(m, b)
}
func (m *JwtGenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtGenerateRequest.Marshal(b, m, deterministic)
}
func (m *JwtGenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtGenerateRequest.Merge(m, src)
}
func (m *JwtGenerateRequest) XXX_Size() int {
	return xxx_messageInfo_JwtGenerateRequest.Size(m)
}
func (m *JwtGenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtGenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JwtGenerateRequest proto.InternalMessageInfo

func (m *JwtGenerateRequest) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *JwtGenerateRequest) GetShort() bool {
	if m != nil {
		return m.Short
	}
	return false
}

func (m *JwtGenerateRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *JwtGenerateRequest) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type JwtCheck struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JwtCheck) Reset()         { *m = JwtCheck{} }
func (m *JwtCheck) String() string { return proto.CompactTextString(m) }
func (*JwtCheck) ProtoMessage()    {}
func (*JwtCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{3}
}

func (m *JwtCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtCheck.Unmarshal(m, b)
}
func (m *JwtCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtCheck.Marshal(b, m, deterministic)
}
func (m *JwtCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtCheck.Merge(m, src)
}
func (m *JwtCheck) XXX_Size() int {
	return xxx_messageInfo_JwtCheck.Size(m)
}
func (m *JwtCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtCheck.DiscardUnknown(m)
}

var xxx_messageInfo_JwtCheck proto.InternalMessageInfo

func (m *JwtCheck) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type JwtResponse struct {
	Error                bool            `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Status               int32           `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Data                 *_struct.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Message              string          `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *JwtResponse) Reset()         { *m = JwtResponse{} }
func (m *JwtResponse) String() string { return proto.CompactTextString(m) }
func (*JwtResponse) ProtoMessage()    {}
func (*JwtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{4}
}

func (m *JwtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtResponse.Unmarshal(m, b)
}
func (m *JwtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtResponse.Marshal(b, m, deterministic)
}
func (m *JwtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtResponse.Merge(m, src)
}
func (m *JwtResponse) XXX_Size() int {
	return xxx_messageInfo_JwtResponse.Size(m)
}
func (m *JwtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JwtResponse proto.InternalMessageInfo

func (m *JwtResponse) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *JwtResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *JwtResponse) GetData() *_struct.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *JwtResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Blank)(nil), "jwt.Blank")
	proto.RegisterType((*HealthResponse)(nil), "jwt.HealthResponse")
	proto.RegisterType((*JwtGenerateRequest)(nil), "jwt.JwtGenerateRequest")
	proto.RegisterType((*JwtCheck)(nil), "jwt.JwtCheck")
	proto.RegisterType((*JwtResponse)(nil), "jwt.JwtResponse")
}

func init() { proto.RegisterFile("jwt.proto", fileDescriptor_b5cacc9c239fa0c7) }

var fileDescriptor_b5cacc9c239fa0c7 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xa6, 0x6e, 0xec, 0x09, 0x7f, 0xa2, 0xa1, 0xa2, 0x56, 0xd4, 0x43, 0xe4, 0x53,
	0x04, 0x92, 0x2d, 0x85, 0x33, 0x17, 0x10, 0x2a, 0xb2, 0xe0, 0xb2, 0x7d, 0x82, 0xad, 0x33, 0xc4,
	0x71, 0x83, 0xd7, 0xec, 0x8e, 0xbb, 0x48, 0x88, 0x4b, 0x78, 0x04, 0x1e, 0x8d, 0x17, 0xe0, 0xc0,
	0x83, 0xa0, 0x5d, 0xdb, 0x91, 0x10, 0x70, 0xe8, 0x6d, 0x3e, 0xcf, 0xb7, 0x3f, 0x7f, 0x33, 0xbb,
	0x10, 0xd7, 0x96, 0xb3, 0x56, 0x2b, 0x56, 0x38, 0xa9, 0x2d, 0x2f, 0x2e, 0xb7, 0x4a, 0x6d, 0xf7,
	0x94, 0xcb, 0x76, 0x97, 0xcb, 0xa6, 0x51, 0x2c, 0x79, 0xa7, 0x1a, 0xd3, 0x5b, 0x8e, 0x5d, 0xaf,
	0x6e, 0xba, 0x0f, 0xb9, 0x61, 0xdd, 0x95, 0x03, 0x20, 0x9d, 0x42, 0xf8, 0x6a, 0x2f, 0x9b, 0xdb,
	0xf4, 0x19, 0x3c, 0x7a, 0x4b, 0x72, 0xcf, 0x95, 0x20, 0xd3, 0xaa, 0xc6, 0x10, 0x26, 0x30, 0xfd,
	0x48, 0xc6, 0xc8, 0x2d, 0x25, 0xc1, 0x32, 0x58, 0xc5, 0x62, 0x94, 0xe9, 0xb7, 0x00, 0xb0, 0xb0,
	0x7c, 0x45, 0x0d, 0x69, 0xc9, 0x24, 0xe8, 0x53, 0x47, 0x86, 0x71, 0x0e, 0x13, 0xfa, 0xdc, 0x7a,
	0x73, 0x28, 0x5c, 0x89, 0xe7, 0x10, 0x9a, 0x4a, 0x69, 0x4e, 0x4e, 0x96, 0xc1, 0x2a, 0x12, 0xbd,
	0x70, 0xe0, 0xf7, 0x03, 0xf8, 0xb4, 0x07, 0x0f, 0x12, 0x9f, 0xc3, 0xe9, 0x46, 0xb2, 0x4c, 0x26,
	0xcb, 0x60, 0x35, 0x5b, 0x5f, 0x64, 0x7d, 0xf4, 0x6c, 0x8c, 0x9e, 0x5d, 0xfb, 0xe8, 0xc2, 0x9b,
	0xd2, 0x4b, 0x88, 0x0a, 0xcb, 0xaf, 0x2b, 0x2a, 0x6f, 0xdd, 0xaf, 0x6b, 0xcb, 0x43, 0x4e, 0x57,
	0xa6, 0x87, 0x00, 0x66, 0x85, 0xe5, 0xe3, 0x34, 0xe7, 0x10, 0x92, 0xd6, 0x4a, 0x7b, 0x4f, 0x24,
	0x7a, 0x81, 0x4f, 0xe1, 0xcc, 0xb0, 0xe4, 0xce, 0xf8, 0x84, 0xa1, 0x18, 0xd4, 0xbd, 0x82, 0xfc,
	0x7f, 0x9e, 0xf5, 0xcf, 0x00, 0xa0, 0xb0, 0x7c, 0x4d, 0xfa, 0x6e, 0x57, 0x12, 0xbe, 0x83, 0xd9,
	0xb8, 0xb3, 0xc2, 0x32, 0x5e, 0x64, 0xee, 0x22, 0xff, 0x5e, 0xe4, 0x62, 0x3e, 0x36, 0xc6, 0xf4,
	0x29, 0x1e, 0x7e, 0xfc, 0xfa, 0x7e, 0xf2, 0x00, 0x21, 0xbf, 0x5b, 0xe7, 0xd4, 0x94, 0x6a, 0x43,
	0xf8, 0x06, 0x22, 0x3f, 0xbc, 0x43, 0x3d, 0x1c, 0x4f, 0xf8, 0x2f, 0xff, 0x00, 0x24, 0x1e, 0x80,
	0x38, 0x77, 0x80, 0x0d, 0x39, 0x40, 0xfe, 0xa5, 0xb6, 0xfc, 0x15, 0x5f, 0x42, 0x7c, 0x45, 0xdc,
	0xdf, 0x3d, 0x82, 0x3f, 0xe8, 0x5f, 0xc4, 0xe2, 0x89, 0xaf, 0xff, 0x7c, 0x14, 0xe9, 0x63, 0xcf,
	0x89, 0x71, 0x9a, 0x57, 0xbe, 0x71, 0x73, 0xe6, 0x77, 0xf2, 0xe2, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x21, 0xa9, 0xf6, 0xfa, 0x95, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JwtServiceClient is the client API for JwtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JwtServiceClient interface {
	// Generates jwt
	GenerateJwt(ctx context.Context, in *JwtGenerateRequest, opts ...grpc.CallOption) (*JwtResponse, error)
	CheckJwt(ctx context.Context, in *JwtCheck, opts ...grpc.CallOption) (*JwtResponse, error)
	// Gets health status - it should check database connection etc ..
	GetHealth(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*HealthResponse, error)
}

type jwtServiceClient struct {
	cc *grpc.ClientConn
}

func NewJwtServiceClient(cc *grpc.ClientConn) JwtServiceClient {
	return &jwtServiceClient{cc}
}

func (c *jwtServiceClient) GenerateJwt(ctx context.Context, in *JwtGenerateRequest, opts ...grpc.CallOption) (*JwtResponse, error) {
	out := new(JwtResponse)
	err := c.cc.Invoke(ctx, "/jwt.JwtService/GenerateJwt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServiceClient) CheckJwt(ctx context.Context, in *JwtCheck, opts ...grpc.CallOption) (*JwtResponse, error) {
	out := new(JwtResponse)
	err := c.cc.Invoke(ctx, "/jwt.JwtService/CheckJwt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServiceClient) GetHealth(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/jwt.JwtService/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtServiceServer is the server API for JwtService service.
type JwtServiceServer interface {
	// Generates jwt
	GenerateJwt(context.Context, *JwtGenerateRequest) (*JwtResponse, error)
	CheckJwt(context.Context, *JwtCheck) (*JwtResponse, error)
	// Gets health status - it should check database connection etc ..
	GetHealth(context.Context, *Blank) (*HealthResponse, error)
}

// UnimplementedJwtServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJwtServiceServer struct {
}

func (*UnimplementedJwtServiceServer) GenerateJwt(ctx context.Context, req *JwtGenerateRequest) (*JwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateJwt not implemented")
}
func (*UnimplementedJwtServiceServer) CheckJwt(ctx context.Context, req *JwtCheck) (*JwtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckJwt not implemented")
}
func (*UnimplementedJwtServiceServer) GetHealth(ctx context.Context, req *Blank) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}

func RegisterJwtServiceServer(s *grpc.Server, srv JwtServiceServer) {
	s.RegisterService(&_JwtService_serviceDesc, srv)
}

func _JwtService_GenerateJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtGenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).GenerateJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwt.JwtService/GenerateJwt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).GenerateJwt(ctx, req.(*JwtGenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtService_CheckJwt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtCheck)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).CheckJwt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwt.JwtService/CheckJwt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).CheckJwt(ctx, req.(*JwtCheck))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwt.JwtService/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).GetHealth(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

var _JwtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jwt.JwtService",
	HandlerType: (*JwtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateJwt",
			Handler:    _JwtService_GenerateJwt_Handler,
		},
		{
			MethodName: "CheckJwt",
			Handler:    _JwtService_CheckJwt_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _JwtService_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwt.proto",
}
